language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
install:
    - pip install . --use-mirrors
    - pip install requests --use-mirrors
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 --use-mirrors; fi"
script: nosetests
branches:
    only:
        - master
notifications:
    email:
        - qmagico-dev@googlegroups.com