language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install . --use-mirrors
    - pip install requests --use-mirrors
    - pip install flake8 --use-mirrors
    - pip install mock --use-mirrors
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 --use-mirrors; fi"
script:
    - nosetests
    - flake8 --ignore=E501 assembla
branches:
    only:
        - master
notifications:
    email:
        - qmagico-dev@googlegroups.com